name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuración básica
          user: korearn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          
          # Ajustes de visualización
          config_display: large
          config_padding: 0, 8%

          # Sección de lenguajes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          # Sección de calendario 3D
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
